service: stepfunction-learning

provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
  stage: dev

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  hello:
    handler: bin/hello
  world:
    handler: bin/world

stepFunctions:
  stateMachines:
    hellostepfunc:
      events:
        - http:
            path: hello
            method: GET
      definition:
        Comment: "A Hello World example of the Amazon States Language using an AWS Lambda Function"
        StartAt: Hello
        States:
          Hello:
            Type: Task
            Resource: hello
            End: true

plugins:
  - serverless-step-functions
