service: stepfunction-learning

provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
  stage: dev

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  hello:
    handler: bin/hello
  world:
    handler: bin/world

stepFunctions:
  stateMachines:
    hellostepfunc:
      events:
        - http:
            path: hello
            method: GET
      definition:
        Comment: "A Hello World example of the Amazon States Language using an AWS Lambda Function"
        StartAt: FirstState
        States:
          FirstState:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-hello
            Next: ChoiceState
          ChoiceState:
            Type: Choice
            Choices:
            - Variable: "$.message"
              StringEquals: "Go Serverless v1.0! Your function executed successfully!"
              Next: TrueState
            Default: FalseState
          TrueState:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-world
            End: true
          FalseState:
            Type: Fail
            Cause: "No Matches!"

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
